#include "script_component.hpp"

class CfgPatches 
{
    class ADDON 
    {
        name = COMPONENT_NAME;
        units[] = {
            // base vehicles
            "A3U_Vehicle_Car_Base",
            "A3U_Vehicle_APC_Base",
            "A3U_Vehicle_Tank_Base",
            "A3U_Vehicle_Ship_Base",
            "A3U_Vehicle_Heli_Base",
            "A3U_Vehicle_Plane_Base",
            "A3U_Vehicle_StaticWeapon_Base",
            "A3U_Vehicle_StaticMortar_Base",

            // rebel units
            "A3U_Rebels_Base",
            "A3U_Rebels_Rifleman",
            "A3U_Rebels_SquadLeader",
            "A3U_Rebels_staticCrew",
            "A3U_Rebels_Medic",
            "A3U_Rebels_Engineer",
            "A3U_Rebels_ExplosivesExpert",
            "A3U_Rebels_Grenadier",
            "A3U_Rebels_LAT",
            "A3U_Rebels_AT",
            "A3U_Rebels_AA",
            "A3U_Rebels_MachineGunner",
            "A3U_Rebels_Marksman",
            "A3U_Rebels_Sniper",
            "A3U_Rebels_Unarmed",

            // rebel vehicles
            "A3U_Rebels_Vehicle_Basic",
            "A3U_Rebels_Vehicle_LightUnarmed",
            "A3U_Rebels_Vehicle_LightArmed",
            "A3U_Rebels_Vehicle_Truck",
            "A3U_Rebels_Vehicle_AT",
            "A3U_Rebels_Vehicle_AA",
            "A3U_Rebels_Vehicle_CivCar",
            "A3U_Rebels_Vehicle_CivTruck",
            "A3U_Rebels_Vehicle_Boat",
            "A3U_Rebels_Vehicle_CivBoat",
            "A3U_Rebels_Vehicle_CivHeli",
            "A3U_Rebels_Vehicle_Plane",
            "A3U_Rebels_Vehicle_CivPlane",
            "A3U_Rebels_Vehicle_StaticMG",
            "A3U_Rebels_Vehicle_StaticAT",
            "A3U_Rebels_Vehicle_StaticAA",
            "A3U_Rebels_Vehicle_Mortar",

            // occupant units
            "A3U_Occupants_Base",
            "A3U_Occupants_Militia_Rifleman",
            "A3U_Occupants_Militia_SquadLeader",
            "A3U_Occupants_Militia_staticCrew",
            "A3U_Occupants_Militia_Medic",
            "A3U_Occupants_Militia_Engineer",
            "A3U_Occupants_Militia_ExplosivesExpert",
            "A3U_Occupants_Militia_Grenadier",
            "A3U_Occupants_Militia_LAT",
            "A3U_Occupants_Militia_AT",
            "A3U_Occupants_Militia_AA",
            "A3U_Occupants_Militia_MachineGunner",
            "A3U_Occupants_Militia_Marksman",
            "A3U_Occupants_Militia_Sniper",
            "A3U_Occupants_Militia_PatrolSniper",
            "A3U_Occupants_Militia_PatrolSpotter",
            "A3U_Occupants_Military_Rifleman",
            "A3U_Occupants_Military_SquadLeader",
            "A3U_Occupants_Military_staticCrew",
            "A3U_Occupants_Military_Medic",
            "A3U_Occupants_Military_Engineer",
            "A3U_Occupants_Military_ExplosivesExpert",
            "A3U_Occupants_Military_Grenadier",
            "A3U_Occupants_Military_LAT",
            "A3U_Occupants_Military_AT",
            "A3U_Occupants_Military_AA",
            "A3U_Occupants_Military_MachineGunner",
            "A3U_Occupants_Military_Marksman",
            "A3U_Occupants_Military_Sniper",
            "A3U_Occupants_Military_PatrolSniper",
            "A3U_Occupants_Military_PatrolSpotter",
            "A3U_Occupants_Elite_Rifleman",
            "A3U_Occupants_Elite_SquadLeader",
            "A3U_Occupants_Elite_staticCrew",
            "A3U_Occupants_Elite_Medic",
            "A3U_Occupants_Elite_Engineer",
            "A3U_Occupants_Elite_ExplosivesExpert",
            "A3U_Occupants_Elite_Grenadier",
            "A3U_Occupants_Elite_LAT",
            "A3U_Occupants_Elite_AT",
            "A3U_Occupants_Elite_AA",
            "A3U_Occupants_Elite_MachineGunner",
            "A3U_Occupants_Elite_Marksman",
            "A3U_Occupants_Elite_Sniper",
            "A3U_Occupants_SpecialForces_Rifleman",
            "A3U_Occupants_SpecialForces_SquadLeader",
            "A3U_Occupants_SpecialForces_staticCrew",
            "A3U_Occupants_SpecialForces_Medic",
            "A3U_Occupants_SpecialForces_Engineer",
            "A3U_Occupants_SpecialForces_ExplosivesExpert",
            "A3U_Occupants_SpecialForces_Grenadier",
            "A3U_Occupants_SpecialForces_LAT",
            "A3U_Occupants_SpecialForces_AT",
            "A3U_Occupants_SpecialForces_AA",
            "A3U_Occupants_SpecialForces_MachineGunner",
            "A3U_Occupants_SpecialForces_Marksman",
            "A3U_Occupants_SpecialForces_Sniper",
            "A3U_Occupants_SpecialForces_PatrolSniper",
            "A3U_Occupants_SpecialForces_PatrolSpotter",
            "A3U_Occupants_Police_Standard",
            "A3U_Occupants_Police_SquadLeader",
            "A3U_Occupants_Other_Crew",
            "A3U_Occupants_Other_Pilot",
            "A3U_Occupants_Other_Official",
            "A3U_Occupants_Other_Traitor",
            "A3U_Occupants_Other_Unarmed",

            // occupant vehicles
            "A3U_Occupants_Vehicle_Basic",
            "A3U_Occupants_Vehicle_LightUnarmed",
            "A3U_Occupants_Vehicle_MilitiaCar",
            "A3U_Occupants_Vehicle_Police",
            "A3U_Occupants_Vehicle_LightArmed",
            "A3U_Occupants_Vehicle_MilitiaLightArmed",
            "A3U_Occupants_Vehicle_Truck",
            "A3U_Occupants_Vehicle_CargoTruck",
            "A3U_Occupants_Vehicle_AmmoTruck",
            "A3U_Occupants_Vehicle_RepairTruck",
            "A3U_Occupants_Vehicle_FuelTruck",
            "A3U_Occupants_Vehicle_MilitiaTruck",
            "A3U_Occupants_Vehicle_Medical",
            "A3U_Occupants_Vehicle_AA",
            "A3U_Occupants_Vehicle_AT",
            "A3U_Occupants_Vehicle_APC",
            "A3U_Occupants_Vehicle_LightAPC",
            "A3U_Occupants_Vehicle_MilitiaAPC",
            "A3U_Occupants_Vehicle_IFV",
            "A3U_Occupants_Vehicle_Tank",
            "A3U_Occupants_Vehicle_LightTank",
            "A3U_Occupants_Vehicle_TransportBoat",
            "A3U_Occupants_Vehicle_GunBoat",
            "A3U_Occupants_Vehicle_LightHeli",
            "A3U_Occupants_Vehicle_LightAttackHeli",
            "A3U_Occupants_Vehicle_AttackHeli",
            "A3U_Occupants_Vehicle_TransportHeli",
            "A3U_Occupants_Vehicle_CASPlane",
            "A3U_Occupants_Vehicle_AAPlane",
            "A3U_Occupants_Vehicle_TransportPlane",
            "A3U_Occupants_Vehicle_StaticMG",
            "A3U_Occupants_Vehicle_StaticAT",
            "A3U_Occupants_Vehicle_StaticAA",
            "A3U_Occupants_Vehicle_Mortar",

            // invader units
            "A3U_Invaders_Base",
            "A3U_Invaders_Militia_Rifleman",
            "A3U_Invaders_Militia_SquadLeader",
            "A3U_Invaders_Militia_staticCrew",
            "A3U_Invaders_Militia_Medic",
            "A3U_Invaders_Militia_Engineer",
            "A3U_Invaders_Militia_ExplosivesExpert",
            "A3U_Invaders_Militia_Grenadier",
            "A3U_Invaders_Militia_LAT",
            "A3U_Invaders_Militia_AT",
            "A3U_Invaders_Militia_AA",
            "A3U_Invaders_Militia_MachineGunner",
            "A3U_Invaders_Militia_Marksman",
            "A3U_Invaders_Militia_Sniper",
            "A3U_Invaders_Militia_PatrolSniper",
            "A3U_Invaders_Militia_PatrolSpotter",
            "A3U_Invaders_Military_Rifleman",
            "A3U_Invaders_Military_SquadLeader",
            "A3U_Invaders_Military_staticCrew",
            "A3U_Invaders_Military_Medic",
            "A3U_Invaders_Military_Engineer",
            "A3U_Invaders_Military_ExplosivesExpert",
            "A3U_Invaders_Military_Grenadier",
            "A3U_Invaders_Military_LAT",
            "A3U_Invaders_Military_AT",
            "A3U_Invaders_Military_AA",
            "A3U_Invaders_Military_MachineGunner",
            "A3U_Invaders_Military_Marksman",
            "A3U_Invaders_Military_Sniper",
            "A3U_Invaders_Military_PatrolSniper",
            "A3U_Invaders_Military_PatrolSpotter",
            "A3U_Invaders_Elite_Rifleman",
            "A3U_Invaders_Elite_SquadLeader",
            "A3U_Invaders_Elite_staticCrew",
            "A3U_Invaders_Elite_Medic",
            "A3U_Invaders_Elite_Engineer",
            "A3U_Invaders_Elite_ExplosivesExpert",
            "A3U_Invaders_Elite_Grenadier",
            "A3U_Invaders_Elite_LAT",
            "A3U_Invaders_Elite_AT",
            "A3U_Invaders_Elite_AA",
            "A3U_Invaders_Elite_MachineGunner",
            "A3U_Invaders_Elite_Marksman",
            "A3U_Invaders_Elite_Sniper",
            "A3U_Invaders_SpecialForces_Rifleman",
            "A3U_Invaders_SpecialForces_SquadLeader",
            "A3U_Invaders_SpecialForces_staticCrew",
            "A3U_Invaders_SpecialForces_Medic",
            "A3U_Invaders_SpecialForces_Engineer",
            "A3U_Invaders_SpecialForces_ExplosivesExpert",
            "A3U_Invaders_SpecialForces_Grenadier",
            "A3U_Invaders_SpecialForces_LAT",
            "A3U_Invaders_SpecialForces_AT",
            "A3U_Invaders_SpecialForces_AA",
            "A3U_Invaders_SpecialForces_MachineGunner",
            "A3U_Invaders_SpecialForces_Marksman",
            "A3U_Invaders_SpecialForces_Sniper",
            "A3U_Invaders_SpecialForces_PatrolSniper",
            "A3U_Invaders_SpecialForces_PatrolSpotter",
            "A3U_Invaders_Police_Standard",
            "A3U_Invaders_Police_SquadLeader",
            "A3U_Invaders_Other_Crew",
            "A3U_Invaders_Other_Pilot",
            "A3U_Invaders_Other_Official",
            "A3U_Invaders_Other_Traitor",
            "A3U_Invaders_Other_Unarmed",

            // invader vehicles
            "A3U_Invaders_Vehicle_Basic",
            "A3U_Invaders_Vehicle_LightUnarmed",
            "A3U_Invaders_Vehicle_MilitiaCar",
            "A3U_Invaders_Vehicle_Police",
            "A3U_Invaders_Vehicle_LightArmed",
            "A3U_Invaders_Vehicle_MilitiaLightArmed",
            "A3U_Invaders_Vehicle_Truck",
            "A3U_Invaders_Vehicle_CargoTruck",
            "A3U_Invaders_Vehicle_AmmoTruck",
            "A3U_Invaders_Vehicle_RepairTruck",
            "A3U_Invaders_Vehicle_FuelTruck",
            "A3U_Invaders_Vehicle_MilitiaTruck",
            "A3U_Invaders_Vehicle_Medical",
            "A3U_Invaders_Vehicle_AA",
            "A3U_Invaders_Vehicle_AT",
            "A3U_Invaders_Vehicle_APC",
            "A3U_Invaders_Vehicle_LightAPC",
            "A3U_Invaders_Vehicle_MilitiaAPC",
            "A3U_Invaders_Vehicle_IFV",
            "A3U_Invaders_Vehicle_Tank",
            "A3U_Invaders_Vehicle_LightTank",
            "A3U_Invaders_Vehicle_TransportBoat",
            "A3U_Invaders_Vehicle_GunBoat",
            "A3U_Invaders_Vehicle_LightHeli",
            "A3U_Invaders_Vehicle_LightAttackHeli",
            "A3U_Invaders_Vehicle_AttackHeli",
            "A3U_Invaders_Vehicle_TransportHeli",
            "A3U_Invaders_Vehicle_CASPlane",
            "A3U_Invaders_Vehicle_AAPlane",
            "A3U_Invaders_Vehicle_TransportPlane",
            "A3U_Invaders_Vehicle_StaticMG",
            "A3U_Invaders_Vehicle_StaticAT",
            "A3U_Invaders_Vehicle_StaticAA",
            "A3U_Invaders_Vehicle_Mortar",

            // rival units
            "A3U_Rivals_Base",
            "A3U_Rivals_Partisan",
            "A3U_Rivals_Mercenary",
            "A3U_Rivals_Minuteman",
            "A3U_Rivals_Enforcer",
            "A3U_Rivals_CellLeader",
            "A3U_Rivals_Commander",
            "A3U_Rivals_Medic",
            "A3U_Rivals_ExplosivesExpert",
            "A3U_Rivals_Saboteur",
            "A3U_Rivals_SpecialistAT",
            "A3U_Rivals_SpecialistAA",
            "A3U_Rivals_Oppressor",
            "A3U_Rivals_Sharpshooter",
            "A3U_Rivals_Crew",
            "A3U_Rivals_Pilot",
            "A3U_Rivals_Unarmed",

            // rival vehicles
            "A3U_Rivals_Vehicle_LightUnarmed",
            "A3U_Rivals_Vehicle_LightArmed",
            "A3U_Rivals_Vehicle_Truck",
            "A3U_Rivals_Vehicle_APC",
            "A3U_Rivals_Vehicle_Tank",
            "A3U_Rivals_Vehicle_Heli",
            "A3U_Rivals_Vehicle_StaticWpn",
            "A3U_Rivals_Vehicle_Mortar",

            // civilian units
            "A3U_Civilians_Base",
            "A3U_Civilians_Man",
            "A3U_Civilians_Press",
            "A3U_Civilians_Worker"
        };
        weapons[] = {};
        requiredVersion = REQUIRED_VERSION;
        requiredAddons[] = {"A3A_Events", "A3_Characters_F"};
        author = AUTHOR;
        authors[] = { AUTHORS };
        authorUrl = "";
        VERSION_CONFIG;
    };
};

class CBA_Extended_EventHandlers_base; // Needed for CfgVehicles.hpp

#include "cfgFactionClasses.hpp"
#include "cfgEditorSubcategories.hpp"
#include "cfgVehicles.hpp"
#include "cfgGroups.hpp"

//the pre proccessor ifs are there to make sure we overwrite/add to the correct config
class A3U
{
    #if __A3_DEBUG__
        #include "CfgFunctions.hpp"
    #endif
};

#if __A3_DEBUG__
#else
    #include "CfgFunctions.hpp"
#endif
